# Copyright 2024 Dylan Stephano-Shachter
# See CONTENT_LICENSE file for licensing details.

name="Jenkins Quality Barbecue"
image="jenkins.jpg"
post='''
Jenkins Quality Barbecue is a small barbecue joint in Jacksonville, Florida. Don’t let the unassuming building deceive you. This place has some serious food. Get a rib sandwich and you will never forget it. The sandwich is a slab of ribs on the bone smothered in sauce between slices of white bread. It’s too messy to actually eat as a sandwich but who cares? There are 3 locations and I think I went to the one downtown (though I’m not sure). If you get a chance to go, it’s definitely worth adding a couple hours to your road trip.
'''
continent="North America"
country="USA"
region="Florida"
