# Copyright 2024 Dylan Stephano-Shachter
# See CONTENT_LICENSE file for licensing details.

name="Rich J.C."
image="rich_jc.jpg"
post='''
Rich J.C. is a small Korean restaurant in Ann Arbor, Michigan. It is one long counter with barely enough room to squeeze by behind the happy customers. This place has by far the best Korean food of anywhere I have eaten. There are lots of delicious items on the menu (and a few that might make westerners uncomfortable), but the “spicy pork” stands head and shoulders above the rest. It is the perfect stir fry of pork and veggies. So good, in fact, that I had it two to three times per week while attending UofM.
'''
continent="North America"
country="USA"
region="Michigan"
location="https://maps.app.goo.gl/wSVCN2VCyZk9yrXPA"
